name: Run E2E Tests

on: [pull_request]

jobs:
  run-e2e-tests:
    name: Run E2E Tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: bitnami/postgresql
        ports:
          - 5432:5432
        env:
          POSTGRESQL_USERNAME: docker
          POSTGRESQL_PASSWORD: docker
          POSTGRESQL_DATABASE: apisolid
        options: > 
          --health-cmd='pg_isready -U docker'
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 9.9.0

      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'pnpm'

      - run: pnpm install

      - run: npx prisma generate 

      - run: pnpm run test:e2e -- --maxWorkers=2 || echo "Tests failed"
        env:
          JWT_SECRET: testing
          DATABASE_URL: "postgresql://docker:docker@postgres:5432/apisolid?schema=public"
